Markdown Table doesn't have side borders
the-i-engineers/tie-gradle-plugins pull request #13
Opened 2023-04-12 08:26 UTC by tiekom

- update tests
- create tableFormat method

2023-04-12 08:36 UTC, fhirt requested changes
bitte noch im README.md das Beispiel aktualisieren

2023-04-12 08:36 UTC, fhirt commented on src/test/java/ch/tie/gradle/plugins/json2md/Json2MdConverterUtilTest.java
> +            "| name2 | type2 | description2 | 2 | \n"));
hier kannst du gleich textblocks einführen: https://www.baeldung.com/java-multiline-string
dann braucths auch die //@formatter Anweisungen nicht mehr

2023-04-12 14:06 UTC, tiekom commented on src/test/java/ch/tie/gradle/plugins/json2md/Json2MdConverterUtilTest.java
> +            "| name2 | type2 | description2 | 2 | \n"));
han gmacht

2023-04-13 15:46 UTC, fhirt requested changes
README.md bitte noch aktualisieren

2023-04-19 06:44 UTC, ozzi- approved these changes
NIT: Was ist der Unterschied wenn das Markdown gerendert wird?

2023-04-19 06:55 UTC, fhirt approved these changes

2023-04-19 06:58 UTC, merged